{{- if .Values.services.ingress.enabled }}
{{- if .Values.services.ingress.x509.ca }}
kind: Secret
apiVersion: v1

metadata:
  name: keystone-x509-ca
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keystone
    type: x509-ca
data:
  ca.crt: {{ .Values.services.ingress.x509.ca | b64enc }}
---
{{- end }}
{{- if .Values.services.public.tlsCertificate}}
kind: Secret
apiVersion: v1

metadata:
  name: tls-{{.Values.services.public.host}}-{{.Values.global.region}}-{{.Values.global.tld | replace "." "-" }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keystone
    type: config
  annotations:
    # only create once and never touch again, since it should be updated via a k8s operator
    #"helm.sh/hook": pre-install, post-upgrade
data:
  tls.crt: {{ .Values.services.public.tlsCertificate | b64enc }}
  tls.key: {{ .Values.services.public.tlsKey | b64enc }}
---
{{- end }}
{{- if .Values.services.admin.tlsCertificate}}
kind: Secret
apiVersion: v1

metadata:
  name: tls-{{.Values.services.admin.host}}-{{.Values.global.region}}-{{.Values.global.tld | replace "." "-" }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keystone
    type: config
  annotations:
    # only create once and never touch again, since it should be updated via a k8s operator
    #"helm.sh/hook": pre-install, post-upgrade

data:
  tls.crt: {{ .Values.services.admin.tlsCertificate | b64enc }}
  tls.key: {{ .Values.services.admin.tlsKey | b64enc }}
---
{{- end }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keystone
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    component: keystone
    type: api
  annotations:
    # clear the trusted key header from external requests
    ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Trusted-Key        "";
    {{- if .Values.services.ingress.limitRps }}
    ingress.kubernetes.io/limit-rps: {{ .Values.services.ingress.limitRps | quote }}
    {{- end }}
    {{- if .Values.services.ingress.limitConnections }}
    ingress.kubernetes.io/limit-connections: {{ .Values.services.ingress.limitConnections | quote }}
    {{- end }}
    {{- if .Values.services.ingress.x509.ca }}
    ingress.kubernetes.io/auth-tls-secret: {{ .Release.Namespace }}/keystone-x509-ca
    ingress.kubernetes.io/auth-tls-verify-client: "optional"
    ingress.kubernetes.io/auth-tls-verify-depth: "1"
    {{- end }}
    {{- if .Values.services.ingress.vice_president }}
    vice-president: "true"
    {{- end }}
spec:
  tls:
    - secretName: tls-{{.Values.services.public.host}}-{{.Values.global.region}}-{{.Values.global.tld | replace "." "-" }}
      hosts: [{{ .Values.services.public.host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}]
    - secretName: tls-{{.Values.services.admin.host}}-{{.Values.global.region}}-{{.Values.global.tld | replace "." "-" }}
      hosts: [{{ .Values.services.admin.host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}]

  rules:
    - host: {{ .Values.services.public.host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}
      http:
        paths:
        - path: /
          backend:
            serviceName: keystone
            servicePort: {{ default "5000"  .Values.services.public.port }}
    - host: {{ .Values.services.admin.host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}
      http:
        paths:
        - path: /
          backend:
            serviceName: keystone
            servicePort: {{ default "35357" .Values.services.admin.port }}
{{- end }}